### ISSUE TITLE
Welcome Page

### ISSUE THREAD

**Issue by TmWgnr** [TmWgnr/KaffeeNerd#1]
## Value proposition

As an User of KaffeeNerd
I want a Home screen with nice Topicpicture, greeting and Navigationbar
with two Navigationbaritems

## Description

- [Scribble]  ![Startpage](https://github.com/TmWgnr/KaffeeNerd/assets/130451637/09303042-aebd-467a-ae34-2abcf5c981fe)

## Acceptance criteria

- [ ] A heading with the name of the App should displayed(h1).
- [ ] A fullscreen Picture should displayed as Background of the Page
- [ ] A navigationbar at the bottom with two buttons should be displayed

## Tasks

- [ ] Create branch "homepage"
- [ ] Create the WelcomePage component to render the welcome page.
- [ ] Create the AppHeader component to display the app name as an h1 heading.
- [ ] Create the BackgroundImage component to set the fullscreen picture as the background of the page.
- [ ] Create the component Navbar
- [ ] Create the component FavoriteButton
- [ ] Create the component ListButton
- [ ] Render the Navbar within the Welcome Page
- [ ] Render the FavoriteButton within the Navbar
- [ ] Render the ListButton within the Navbar

**Comment by actyvystom** [comment]
A good start! 
Some comments:
Please stick to the correct syntax in your **value proposition**:
e.g. 
> As a user, 
> I want to see a homescreen offering two buttons 
> in order to decide which part of the app I want to see

Probably it will be one button only for the first step as your Favorite button only makes sense if there are already favorites to show...

Get more detailed in your **acceptance criteria**
- Consider the following: 
 - What happens when the user clicks one of the buttons (or the one button as Favorites probably won't be part of your first user story?
 
Your **task list** contains a lot of items (which is nice 🙂), but some of them are doubtful:
- Rendering components is done by next or react, so you should not consider this as a development task
- If you mean to place a certain component then better describe it as e.g. 
> implement component `Xyz` in Page-Component `Home`

**Comment by FelineHuhn** [comment]
Hey Tim. nice work so far. ✨ 
I am just wondering if such a landing page wouldn't be more suitable for a later user story and you better create a coffee bean list as the first user story? Because both the favourite button and the kaffeebohnen button would not have any function yet, or? What do you think about that?

**Comment by sebastianwel** [comment]
looks good to me. Only tiny thing is that I understood that we do not need to mention the name of the html-tags e.g. "h1" in the acceptance criteria. besides that I think it looks solid now and you can work this out.

**Comment by TmWgnr** [comment]
thanks @sebastianwel I deleted the h1 in the criteria.
