### ISSUE TITLE
coffee-input-form2

### ISSUE THREAD

**Issue by TmWgnr** [TmWgnr/KaffeeNerd#10]
## Value Proposition

**As a**   
**I want to** have more specific inputfields
**so that** I can be more specific in adding my tested coffees
​

## Description

![image](https://github.com/TmWgnr/KaffeeNerd/assets/130451637/63236ce4-0114-4675-868f-d18fc199407c)

​

## Acceptance Criteria

- [ ] The header "Neue Bohne" is displayed
- [ ] "Aroma" should have two values with radioboxes called "beerig/
fruchtig" and "schokoladig/nussig"
- [ ] The input field "Mahlgrad" is displayed, accepts  numbers, focuses on click
- [ ] one dropdown is displayed for gram 
- [ ] one dropdown is displayed for ml
- [ ] both dropdowns called "in/out"
- [ ] The AddButton "hinzufügen" is displayed
- [ ] The CancelButton "Abbrechen" is displayed
- [ ] Clicking Add button shows the Coffee in the KaffeeListe
- [ ] The navbar is displayed
      ​

## Tasks

- [ ]  Create branch coffee-input-form2
- [ ]  Add Inputfields to CoffeeInputForm
- [ ]  Write function for CancelButton
- [ ] render footer in CoffeeInputform

**Comment by RonnySteady** [comment]
Hi Tim,

a few suggestions:

- radioboxes called radio buttons I think, you could make clear that the selection is either/or, not both 

- your tasks should include the
 > implementation of the dropdown menus
 > description of the button "hinzufügen"  

- in tasks you mention the footer, quite sure this is the navbar you mentioned as criteria, if so chose the same names 

Cheers, Ronald

**Comment by TmWgnr** [comment]
> Hi Tim,
> 
> a few suggestions:
> 
> * radioboxes called radio buttons I think, you could make clear that the selection is either/or, not both
> * your tasks should include the
> 
> > implementation of the dropdown menus
> > description of the button "hinzufügen"
> 
> * in tasks you mention the footer, quite sure this is the navbar you mentioned as criteria, if so chose the same names
> 
> Cheers, Ronald

thank you ronald fo ur suggestions. i changed all unless "hinzufügen" button because its allready done in US5.
