### ISSUE TITLE
US7: add Listitem

### ISSUE THREAD

**Issue by TmWgnr** [TmWgnr/KaffeeNerd#11]
## Value Proposition

**As a** user
**I want to** see my added coffes in my "coffelist" with a add button
**so that**  i can add another coffee
​

## Description

![image](https://github.com/TmWgnr/KaffeeNerd/assets/130451637/74b079a2-0aed-4b85-ac4f-c3340bccdb94)​

## Acceptance Criteria

- [ ] the added/new Coffee should displayed in my Kaffeliste
- [ ] the "Kaffeliste" should have a button which heading to create page below the listcard​

## Tasks

- [ ] create a new branch
- [ ] render the formentries in the component Coffelist
- [ ] ceate a new addButton component
- [ ] render addButton in CoffeeList

**Comment by MariaRiosNavarro** [comment]
Hey Tim, i need a coffee... you have a small mistakeTypo issue in Acceptance Criteria:

the added/new Coffee should displayed in my Kaffeliste

Do you mean Kaffeeliste?
☕️ ☕️ ☕️

**Comment by TmWgnr** [comment]
oh thank u.

come to hamburg and you´ll get ur coffee- as many as you want :)
