### ISSUE TITLE
US8: hide/show Listitem

### ISSUE THREAD

**Issue by TmWgnr** [TmWgnr/KaffeeNerd#12]
## Value Proposition

**As a** User 
**I want to** hide/show my Listitems
**so that** i can see a few listitems when hide and all cardcontent of one item when show is clicked
​

## Description

![image](https://github.com/TmWgnr/KaffeeNerd/assets/130451637/63274f11-ae48-4c71-8e3c-a9c74cadf3ba)

## Acceptance Criteria

- [ ] the list should have two options depending on the condition
- [ ] if opening the list all item should hide
- [ ] all item should have the button "show"
- [ ] if "show" ist clicked, the hole cad content opens
      ​

## Tasks

- [ ] create a new branch
- [ ] create a button component 
- [ ] implement a function to toggle 
- [ ] render the button in the card componente

**Comment by sebastianwel** [comment]
LGTM, only one small typo in the AC "card" not cad :D

**Comment by TmWgnr** [comment]
merci :)
