### ISSUE TITLE
US9: Favorite Button

### ISSUE THREAD

**Issue by TmWgnr** [TmWgnr/KaffeeNerd#13]
## Value Proposition

**As a** user
**I want to** favourite my coffees
**in order to** have the oportunity to save my favourite Coffes
​

## Description

![image](https://github.com/TmWgnr/KaffeeNerd/assets/130451637/fc7ce43b-00b3-46d2-9e59-a12fea9eb717)
​

## Acceptance Criteria

- [ ] a empty star icon should displayed in each listitem
- [ ] when clicking the star it should be filled
- [ ] when clicking again it should remove from filled icon
- [ ] the favourite status should persist even after refreshing the page
      ​

## Tasks

- [ ] create a new branch
- [ ] implement the favourite-icon to each coffee entry in the list
- [ ] set up an event handler to toggle the favourite status
- [ ] implement a mechanism to persist the status(local storage)

**Comment by JonasDaJones** [comment]
jo, that local storage makes sense
