### ISSUE TITLE
US9: edit Listitem

### ISSUE THREAD

**Issue by TmWgnr** [TmWgnr/KaffeeNerd#17]
## Value Proposition

**As a** User
**I want to** edit my  added listitems
**so that/in order to** i can change data (e.g. country)

## Description

![image](https://github.com/TmWgnr/KaffeeNerd/assets/130451637/bd7e2e2f-326d-49b3-9df9-186ee2e55101)
​

## Acceptance Criteria

- [ ] The application should provide an edit functionality for list items.
- [ ] When the user selects the edit option for a specific list item, a form or modal should be displayed.
- [ ] The form or modal should pre-fill the fields with the existing data of the list item.
- [ ] The user should be able to modify the data
- [ ] After making the necessary changes, the user should be able to save the edits.
- [ ] The updated data should be reflected in the list view.
- [ ] If the user decides to cancel the edit, the original data should remain unchanged.

      ​

## Tasks

- [ ] create feature branch
- [ ] Add an edit button for each listItem
- [ ] Implement a form component to display when the user selects the edit option.
- [ ] fill the form fields with the existing data of the selected list item.
- [ ] Allow the user to modify the data in the form.
- [ ] Implement a save functionality to update the list item with the edited data.
- [ ] Update the list view to reflect the changes immediately after saving the edits.
- [ ] Implement a cancel functionality to discard the edits and keep the original data.

**Comment by actyvystom** [comment]
A nice one! 👍🏻 
Just some tiny comments regarding your **acceptance criteria**: 
- you mention an _edit option_ which the user can select. In your wireframe I see a pen icon, so I guess this would be some kind of button to trigger your edit mode, right?
- So you should add this behaviour also to your acceptance criteria (and also as a task in your task list)

In your **value proposition**, please remove one of the text templates _so that/in order to_ and try to avoid technical language like listitem, data, etc., e.g.

> as a user
> I want to be able to edit information about a coffee 
> in order to save this changed information
