### ISSUE TITLE
US10: delete button

### ISSUE THREAD

**Issue by TmWgnr** [TmWgnr/KaffeeNerd#18]
## Value Proposition

**As a** User
**I want to** have a deletebutton on Listitems
**so that/in order to** i can delete Listitems
​

## Description

![image](https://github.com/TmWgnr/KaffeeNerd/assets/130451637/8232b150-d249-4467-a423-1ae95c3592cc)
​

## Acceptance Criteria

- [ ]  The application should provide an delete functionality for list items.
- [ ]  When the user selects the delete option for a specific list item, the list item should be deleted
- [ ]  The updated list should be reflected in the list view.
- [ ]  The user should get asked if he is sure to delete item?
      ​

## Tasks

- [ ] create feature branch
- [ ] Add a delete option/button for each list item in the UI.
- [ ] Implement a confirmation dialog so  that  the user has confirm the deletion.
- [ ] When the user selects the delete option, display the confirmation dialog
- [ ] If the user confirms the deletion, remove the selected list item from the list.
- [ ] Update the list view to reflect the updated list without the deleted item.
- [ ] If the user cancels the deletion, close the confirmation dialog/modal without performing any deletion.

**Comment by ThysBat** [comment]
LGTM! 🚀
