### ISSUE TITLE
ListPage

### ISSUE THREAD

**Issue by TmWgnr** [TmWgnr/KaffeeNerd#2]
## Title

UserStory2: Listpage

## Value proposition

As an User of KaffeeNerd
I want a Page where i can see my "tested" coffees in a list.
I want to  have button where i can add coffeevariety.
i want to have button where i can delete coffeevariety.

## Description

![image](https://github.com/TmWgnr/KaffeeNerd/assets/130451637/f638fc52-52e1-4637-9fdd-338d564f164f)
## Acceptance criteria

- [ ] A heading with the name of the List should displayed(h1).
- [ ] A Listitem views three main criteria of the Coffee
- [ ] A navigationbar at the bottom with two buttons should be displayed
- [ ] A plus symbol should (createbutton) displayed (no function yet)
- [ ] A hide/show button should displayed on each Listitem

## Tasks

- [ ] Create CoffeeList component
- [ ] Create 
- [ ] 
- [ ]
- [ ]

**Comment by mbosselmann** [comment]
Hi Tim,
great job! 💪 I only have one remark that you should consider. Your value proposition is not complete as you did not mention the benefit of your feature. My suggestion:

**As a** user
**I want to** have a list of several coffees
**so that** I get an overview about which coffees are available

- I am not sure if it is the user's collection of coffees that he has at home or something else, but this is something you can could also clarify in your value proposition

Everything else looks good! Nothing else to add from my side. :)

**Comment by TmWgnr** [comment]
@mbosselmann thank you:) 

i changed my Value proposition a bit. 
hope, i can now do my second US ?! 🤩
