### ISSUE TITLE
US: consistent design

### ISSUE THREAD

**Issue by TmWgnr** [TmWgnr/KaffeeNerd#21]
## Value Proposition

**As a** user
**I want to** see a consistent designed App
**in order to** have a good overview where I get along well
​

## Description

The App has 4 pages. 
except the home page, which has a backgroundimage,
all off them should have the same theme, and consistent design

​

## Acceptance Criteria

- [ ] The form, list and details pages use the same color scheme
- [ ] To a user it is clear what information he/she needs to put inside the forms
- [ ] All page elements got enough space around each other 
- [ ] All text content is well readable and therefore accessible
      ​

## Tasks

- [ ] Create branch 
- [ ] Apply same color scheme 
- [ ] Adjust the spacing and layout of form fields
- [ ] Check for accessibility regarding readability
- [ ] Edit and create styled components if necessary

**Comment by dimitriosxmi** [comment]
## LGTM clear and straightforward US
Notes: Wish you all the best with styling and that it takes less than expected! 😊
