### ISSUE TITLE
US: FAVORITETOGGLE

### ISSUE THREAD

**Issue by TmWgnr** [TmWgnr/KaffeeNerd#23]
## Value Proposition

**As a** User
**I want to** have a favorite button
**so that** i can add my favorite coffees in an favorite LIST

## Description

​
![Screenshot 2023-07-05 at 18 39 15](https://github.com/TmWgnr/KaffeeNerd/assets/130451637/bb284df2-b856-4d10-9fa0-69e67df48de6)

## Acceptance Criteria

- [ ] The application should have a "favorite" button/icon associated with each coffee item.
- [ ] Clicking on the "favorite" button should add the coffee item to the user's favorite list.
- [ ] The "favorite" button should visually indicate whether a coffee item has been added to the favorite list or not (e.g., change color or display a filled heart icon).
- [ ]Clicking on the "favorite" button again for an already favorited coffee item should remove it from the favorite list.
- [ ]The application should provide a way for the user to view their favorite list.
- [ ]The favorite list should display the favorited coffee items
- [ ]The user should be able to easily remove coffee items from their favorite list.

      ​

## Tasks

- [ ] Add a "favorite" button/icon to each coffee item
- [ ] Implement the logic to add a coffee item to the favorite list when the "favorite" button is clicked.
- [ ] Implement the visual indication on the "favorite" button to show whether a coffee item is favorited or not.
- [ ] Implement the logic to remove a coffee item from the favorite list when the "favorite" button is clicked again.
- [ ] Create a page to display the user's favorite list.
- [ ] Implement the functionality to remove coffee items from the favorite list.

**Comment by ChristophLeuker** [comment]
Very easy to understand, good work. But one question. Is a different page with a list for the favorites also in this US? There are no specific criteria for that. Maybe add another US for the Page itself and remove the criteria here.

**Comment by TmWgnr** [comment]
it is the penultimate item in the list of tasks?!
