### ISSUE TITLE
Navigationbar

### ISSUE THREAD

**Issue by TmWgnr** [TmWgnr/KaffeeNerd#3]
## Value proposition

As an user
i want to have a navigation bar on startingpage to
get to the listpage

## Description

![image](https://github.com/TmWgnr/KaffeeNerd/assets/130451637/b7ddc207-54da-420a-a5aa-cc5d5d2b1e65)

## Acceptance criteria

- [ ] a navigationbar as a footer should be displayed
- [ ] the navigationbar should have a button
- [ ] clicking the button should open the listpage

## Tasks

- [ ] Create a Branch "navigationbar"
- [ ] Create Footer component
- [ ] Create ListButton component 
- [ ] Create Navigationbar component that renders a Button
