### ISSUE TITLE
Naviagtionbar2

### ISSUE THREAD

**Issue by TmWgnr** [TmWgnr/KaffeeNerd#4]
## Value Proposition

As an user
i want to have a navigation bar on ListPage to
get to the StartPage
​

## Description

![image](https://github.com/TmWgnr/KaffeeNerd/assets/130451637/5fefc48f-6b29-4635-a124-78c4082d3c51)

​

## Acceptance Criteria

 - [ ] a navigationbar as a footer should be displayed
 - [ ] the navigationbar should have a button
 - [ ] clicking the button should open the StartPage     ​

## Tasks

- [ ] Create a Branch "navigationbar2"
- [ ] Create `HomeButton` component
- [ ] Render `HomeButton` in `NavigationBar`

**Comment by nastiche** [comment]
Hi Tim,

I suggest you add both Home and List nav buttons to your description image, because you already created a List nav button in the previous story.

I would also make a few minor changes to make the user story clearer:

Value Proposition:

  As a user
  I want to be able to switch to the Start Page any time
  so that I can see the beautiful logo

Cheers
Nasti

**Comment by TmWgnr** [comment]
i changed my Value Proposition and my scribble
