### ISSUE TITLE
US5: Input-Form

### ISSUE THREAD

**Issue by TmWgnr** [TmWgnr/KaffeeNerd#5]
## Value Proposition

As a user

I want to be able to enter a new coffee with name, herkunft and Sorte
and to add this in the KaffeeListe

## Description

![image](https://github.com/TmWgnr/KaffeeNerd/assets/130451637/a002e927-81b0-4f34-87a8-8e74a1382ca1)​

## Acceptance Criteria

- [ ] The header is displayed
- [ ]  The input field "KaffeeName" is displayed, accepts text value, focuses on click
- [ ]  The input field "Herkunft" is displayed, accepts text value, focuses on click
- [ ]  "Sorte" should have two values with checkboxes called "arabica" and "robusta"
- [ ]  The button Add is displayed
- [ ]  Clicking Add button shows the Coffee in the KaffeeListe 

## Tasks

- [ ] Create branch coffee-input-form
- [ ] Create component CoffeeInputForm
- [ ] Write function for Add button

**Comment by MariaRiosNavarro** [comment]
You should formulate your Value proposition with

 **As a** <user>/<role>
**I want to** <feature>
**so that** <benefit>

thank you
